"""Correct typo in Message

Revision ID: 9839a8c631a4
Revises: c5cb5e2a5ed3
Create Date: 2021-06-09 21:58:28.647851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9839a8c631a4'
down_revision = 'c5cb5e2a5ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message') as batch_op:
        batch_op.drop_column('boday')
    op.add_column('message', sa.Column('body', sa.String(length=140), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('boday', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
